### ISSUE TITLE
Giving permissions to entity to publish returns error

### ISSUE THREAD

**Issue by phgupta** [immesys/wave#23]
Following command gives the error,

wv rtgrant --attester $WAVE_DEFAULT_ENTITY --subject site.ent --expiry 3y --indirections 0 "wavemq:publish@GyARFMRl6uG1jClJUrDlGFydj_8RqCCqmjN96TsOgHaYHg==/test_resource/*"
passphrase for entity secret:
Synchronized 5/6 entities
Synchronized 6/6 entities
Perspective graph sync complete
wrote attestation: att_GyC57_KDoKFAjuKGdWO-fX41C2grfMvZYENcMmsYEir3-Q==.pem
error: (204: could not put attestation (Post https://standalone.storage.bwave.io/v1/obj: x509: certificate has expired or is not yet valid))

Corresponding wave logfile,
Sep 13 16:47:37 pranavhgupta waved[5577]: se Err 1
Sep 13 16:47:37 pranavhgupta waved[5577]: Failed to synchronize entity: Get https://standalone.storage.bwave.io/v1/queue/GyARFMRl6uG1jClJUrDlGFydj_8RqCCqmjN96TsOgHaYHg==?token=2&trusted=0: x509: certificate has expired or is not yet valid

**Comment by immesys** [comment]
This was fixed literally 10 seconds ago :-) 

Try now
