### ISSUE TITLE
Any client libraries?

### ISSUE THREAD

**Issue by jbkoh** [immesys/wave#25]
Hi again. Are there any other client libraries available? Should I just wrap ``wv`` with other languages?

**Comment by immesys** [comment]
The API is a GRPC API, so it's very easy to generate client libraries. We have generated Python and Go but it's quite easy to make other ones

**Comment by jbkoh** [comment]
@immesys Thanks for the information. Great to hear that. Where is the API specification? Is your generated Python client code available?

**Comment by jbkoh** [comment]
Is this the one? https://github.com/immesys/wave/blob/master/waved/cmd/swagger/wave.swagger.json
