### ISSUE TITLE
Mixup between generalized and UTC time in entities when using wv command line tool

### ISSUE THREAD

**Issue by ddreyer** [immesys/wave#9]
When trying to unmarshal an entity that has an expiry using the generated C++ asn1 decoder, this error pops up:
```
D0033E: Tag mismatch or tag not expected: [UNIVERSAL 24] (expected tag [UNIVERSAL 23]); check field 'notAfter' (type: UTCTime) of field 'validity' (type: SEQUENCE) of field 'tbs' (type: SEQUENCE) of PDU #4 (type: WaveEntity) of field 'value' (type: OpenType) of PDU #1 'WaveWireObject'.
          *SKIPPED*: tag = [UNIVERSAL 24] primitive; length = 19
            <skipped>
D0049E: Field omitted: "notAfter"; check field 'validity' (type: SEQUENCE) of field 'tbs' (type: SEQUENCE) of PDU #4 (type: WaveEntity) of field 'value' (type: OpenType) of PDU #1 'WaveWireObject'.
```

~~Seems like there is a discrepancy between using generalized time when creating an entity in eapi.go + iapi/entity.go and in the definition of the entity serdes object~~

**Comment by ddreyer** [comment]
Update: seems this problem happens with the wv command line tool. 

```
$ wv mke -o service.ent --expiry 1y
$ wv mke -o namespace.ent --expiry 40y
$ wv rtgrant --attester namespace.ent --subject service.ent --expiry 1y "wavemq:subscribe,publish,query@namespace.ent/*"
$ wv rtprove --subject service.ent "wavemq:subscribe,publish,query@namespace.ent/*"
$ wv verify proof_2018-12-19T13\:41\:35-08\:00.pem
```

This proof verifies correctly with the command line tool but fails due to wrong time format in the C++ verification code

**Comment by immesys** [comment]
This only happens with large expiries. Something causes things to be encoded differently when the expiry is large. I suspect this is a year 2038 bug

**Comment by immesys** [comment]
ASN.1 only allows a representation of UTC time up to 2050, so any expiry past that time will cause it to be promoted to GeneralizedTime. 

I'm going to triage this as WONTFIX. Lets just avoid 40 year expiries for now
